version: 2
jobs:
  build:
    working_directory: /zmc-docker-base
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Build container'
          command: |
            docker build -t f9teams/zmc-base:${CIRCLE_SHA1} .
      - deploy:
          name: 'Publisher container if master'
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

              docker tag f9teams/zmc-base:${CIRCLE_SHA1} f9teams/zmc-base:latest
              docker tag f9teams/zmc-base:${CIRCLE_SHA1} f9teams/zmc-base:${CIRCLE_BUILD_NUM}

              docker push f9teams/zmc-base:latest f9teams/zmc-base:${CIRCLE_SHA1} \
                          f9teams/zmc-base:${CIRCLE_BUILD_NUM}
            fi
