version: 2
jobs:
  build:
    working_directory: /zmc-docker-base
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: 'Build container'
          command: |
            docker build -t zimbra/zmc-base:latest .
      - deploy:
          name: 'Publisher container if master'
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

              short_sha=$(echo $CIRCLE_SHA1 | cut -c -7)

              docker tag zimbra/zmc-base:latest zimbra/zmc-base:$short_sha
              docker tag zimbra/zmc-base:latest zimbra/zmc-base:${CIRCLE_BUILD_NUM}

              docker push zimbra/zmc-base:latest
              docker push zimbra/zmc-base:$short_sha
              docker push zimbra/zmc-base:${CIRCLE_BUILD_NUM}
            fi
